language: perl
perl:
- 5.18
- 5.16
- 5.14
- 5.12
- 5.10
- 5.8

install:
- wget https://openresty.org/download/openresty-1.11.2.3rc1.tar.gz
- tar -xf openresty-1.11.2.3rc1.tar.gz
- cd openresty-1.11.2.3rc1/ && ./configure -j2 && make -j2 && sudo make install && cd ..
- cpanm --quiet --notest
  File::Find::Rule
  Template
  IPC::Run3

script:
- PATH="/usr/local/openresty/bin:$PATH" prove -j2 -Ilib -r t/
